### ISSUE TITLE
Flair Fasttext .vec extension

### ISSUE THREAD

**Issue by OguzKircicek** [pranaychandekar/fasttext-embeddings-with-flair#3]
Hi ,

Thank you for this study. I have a problem , I want to .vec extension for word embedding using flair framework. 

Example : search_space.add(Parameter.EMBEDDINGS, hp.choice, options=[
    WordEmbeddings("original_rgx.vec") ])

**Comment by pranaychandekar** [comment]
Hey @OguzKircicek , I have added support for your request.
